### ISSUE TITLE
You think this would work

### ISSUE THREAD

**Issue by buzztiaan** [Links2004/arduinoVNC#1]
With a ili9488 screen? i see 320x480 3.5" tft with that driverchip

**Comment by buzztiaan** [comment]
or a ili9486 ?

**Comment by Links2004** [comment]
the VNC part has a clear interface to the Display,
if you implement the interface you can use any display you like.

Interface class:
https://github.com/Links2004/arduinoVNC/blob/master/src/VNC.h#L141-L161

for the ILI9341 as example:
https://github.com/Links2004/arduinoVNC/blob/master/src/VNC_ILI9341.cpp

**Comment by buzztiaan** [comment]
ok i think i'll order one of the 4" ones and get to hacking! sweeeet

**Comment by colesnicov** [comment]
@buzztiaan Any progress?

**Comment by buzztiaan** [comment]
project sidetracked, ended up here ; https://nurdspace.nl/Webpotato
