### ISSUE TITLE
Compatibile with TigerVNC server?

### ISSUE THREAD

**Issue by bob-u** [Links2004/arduinoVNC#25]
Will this client connect to screen scraping VNC server like TigerVNC?

**Comment by Links2004** [comment]
yes, any VNC server will work, as long its implementing rfbproto which is basically all of them.

**Comment by bob-u** [comment]
Great.  I'll try to make it work with Klipperscreen and TigerVNC.  This could be the low cost display solution for Klipper's display.

**Comment by bob-u** [comment]
Works fine with TigerVNC.
