### ISSUE TITLE
Add TRLE/ZRLE encoding support?

### ISSUE THREAD

**Issue by bob-u** [Links2004/arduinoVNC#29]
Would it be possible to add TRLE/ZRLE encoding to the library from here https://github.com/moononournation/ArduinoVNC?

From the comment in the code:
7.7.5. TRLE
 * TRLE stands for Tiled Run-Length Encoding, and combines tiling,
 * palettization, and run-length encoding.  The rectangle is divided
 * into tiles of 16x16 pixels in left-to-right, top-to-bottom order,
 * similar to Hextile.  If the width of the rectangle is not an exact
 * multiple of 16, then the width of the last tile in each row is
 * smaller, and if the height of the rectangle is not an exact multiple
 * of 16, then the height of each tile in the final row is smaller.
 *
 * 7.7.6. ZRLE
 * ZRLE stands for Zlib (see [RFC1950] and [RFC1951]) Run-Length
 * Encoding, and combines an encoding similar to TRLE with zlib
 * compression.  On the wire, the rectangle begins with a 4-byte length
 * field, and is followed by that many bytes of zlib-compressed data.  A
 * single zlib "stream" object is used for a given RFB protocol
 * connection, so that ZRLE rectangles must be encoded and decoded
 * strictly in order.

**Comment by TheNitek** [comment]
I ported the code: https://github.com/Links2004/arduinoVNC/pull/35
