### ISSUE TITLE
hide mouse cursor

### ISSUE THREAD

**Issue by wasn-eu** [Links2004/arduinoVNC#8]
i have to drag the mouse cursor around.
but woud like to just touch the region i want to klick at.
when using my tablet to connect to the vnc server i can just klick the button and dont have to drag the cursor and klick then.

What am i doing wrong?

**Comment by Links2004** [comment]
the mouse cursor is generated at the server side, (if you want to hide it configure your server).
for Xorg there is a ```-nocursor``` option or you use ```unclutter```.

you can send a mouse click at any point you want with 
```cpp
// button down
vnc.mouseEvent(x, y, 0b001); 

// button up
vnc.mouseEvent(lx, ly, 0b000);
```

if you use the touch example simple click where you want on the display.
