### ISSUE TITLE
Scramble Display on TightVNC

### ISSUE THREAD

**Issue by mltongca** [Links2004/arduinoVNC#9]
The display is sort of working with a bit scramble when TightVNC server is connected.

**Comment by Links2004** [comment]
most likely a HW problem at 80Mhz the connections an cables starts to matter.
you can try to change it to 40Mhz and see how it goes, if its fine then, you need to improve you wirering or you display can not handle 80Mhz well.

https://github.com/Links2004/Adafruit_ILI9341/blob/master/Adafruit_ILI9341.cpp#L267

**Comment by mltongca** [comment]
SPI.setFrequency(60000000) function is used to change the SPI clock to 60Mhz and it is working fine now. Thank you.

**Comment by Links2004** [comment]
Note:
the ESP can not run the SPI at 60Mhz it will run at 40Mhz when you call the setFrequency with 60Mhz.
this is a Hardware limitation, based on how the frequency divider works internally.
